# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 007a364bf1c0c6ea10b105c6a5971ba466a963223f8d2b36e9314cd59eeb8968e28f7da827f32b7c05459caa60e6a29cbaffa39c517af40cff29e068240b9ab6

test:
  secret_key_base: 7b516357bec7e89d08560fb4a5a26391b4552bb3921edb879c756a28492eb44eb324fcf91128944ebfa25e3a43bfadf8129a5bc8d7f21c86a96393068b5cd1c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
